<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P9BL872" failures="1" tests="4" name="Surefire test" time="12.421" errors="0" timestamp="2021-02-01T16:48:59 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.273"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.1">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at cucumberHooks.addonFunctions.compareString(addonFunctions.java:81)
at StepsDefine.apiAutomationFunctions.verify_body(apiAutomationFunctions.java:251)
at StepsDefine.apiAutomationFunctions.verify_response_body_for_endpoint(apiAutomationFunctions.java:92)
at âœ½.verify response body for "validate error msg for invalid email"(classpath:features/emersonAPI.feature:68)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.983"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.046"/>
</testsuite> <!-- Surefire test -->
